name: Update Action

on:
  - pull_request

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Update action file with new script urls
    runs-on: ubuntu-latest
    env:
      base_url: 'https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/'
      template_file: 'action-template.yml'
      output_file: 'action.yml'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update action.yml
        run: |
          sed "s|{{base_url}}|${{ env.base_url }}|g" "${{ env.template_file }}" | tee "${{ env.output_file }}"

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Pull latest changes
        run: |
          git pull --rebase origin ${{ github.head_ref }}

      - name: Commit and push action.yml
        run: |
          git add "${{ env.output_file }}"
          git commit -m "Update ${{ env.output_file }} to reflect new release"
          git push origin HEAD:${{ github.head_ref }}

  test:
    name: Test custom npm publish
    runs-on: ubuntu-latest
    needs: build
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Custom Docker Build and Push
        uses: alvelive/publish@v1
        with:
          publish: true
          npm-token: ${{ secrets.GITHUB_TOKEN }}
