name: Check if the changes pass the build

on:
  push:
    branches:
      - v1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  packages: write

jobs:
  update-action:
    runs-on: ubuntu-latest
    steps:
      - name: Update action.yml
        uses: alvelive/update-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          sha: ${{ github.sha }}

  build:
    runs-on: ubuntu-latest
    needs: update-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish the package
        uses: alvelive/publish@v1
        with:
          force: true
          publish: true
          npm-token: ${{ secrets.GITHUB_TOKEN }}
          install-token: ${{ secrets.GITHUB_TOKEN }}
